[package]
name = "wgputris"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytemuck = "1.21"
env_logger = "0.11"
log = "0.4"
pollster = "0.4"
wgpu = "24.0"
winit = { version = "0.30" }
